// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfqrkxngvbptucsmkpkf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmcXJreG5ndmJwdHVjc21rcGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NTUzNjEsImV4cCI6MjA1NTUzMTM2MX0.fPMWkUkOD9UOc4rAEiBQ7_4xD8yxONlitk17dRDXhjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);